<?php
	chong_pha_hoai();
?>
<?php
	if($_GET['thamso']=="xem_gio_hang")
	{
		include("cumchucnang/giohang/thuc_hien_them_vao_gio.php");
	}
	if($_GET['thamso']=="thoat")
	{
		include("cumchucnang/dangky_dangnhap/thoat.php");
		trangtruoc();
		exit();
	}
	if($_SESSION['jac_41']=="co")
	{
		unset($_SESSION['jac_41']);
		chuyentrang("?thamso=xem_gio_hang");
		exit();
	}
	if($_SESSION['jac_82']=="co")
	{
		unset($_SESSION['jac_82']);
		chuyentrang("?thamso=dang_ky");
		exit();
	}
	if($_SESSION['jac_91']=="co")
	{
		unset($_SESSION['jac_91']);
		chuyentrang("index.php");
		exit();
	}
	if(isset($_POST['cap_nhat_gio_hang_abc']))
	{
		include("cumchucnang/giohang/capnhat_giohang.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['gui_don_hang_abc']))
	{
		include("cumchucnang/giohang/gui_don_hang.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['dang_ky_thanh_vien']))
	{
		include("cumchucnang/dangky_dangnhap/thuchien_dangky.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['thuchien_dangnhap__bcd']))
	{
		include("cumchucnang/dangky_dangnhap/thuchien_dangnhap.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['sua_thanh_vien']))
	{
		include("cumchucnang/dangky_dangnhap/sua_thanh_vien.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['gui_lien_he__abc']))
	{
		include("cumchucnang/lien_he/thuc_hien_gui.php");
		trangtruoc();
		exit();
	}
	if(isset($_POST['lay_lai_mat_khau']))
	{
		include("cumchucnang/dangky_dangnhap/thuc_hien_lay_lai_mat_khau.php");
		trangtruoc();
		exit();
	}
?>